In [30]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer



etudiants = pd.read_csv("TB_ETUDIANT.csv", encoding='latin-1', delimiter=";")

#creation de datafram
df = pd.DataFrame(etudiants)

df

,ID_ETUDIANT,Sexe,MoyenneBac,Orientation,NotesMaths,NotesFrançais,NotesPhysiques,NotesChimie,NotesAnglais,Interets_1,Interets_2,ChoixOrientation
0,ET001,NaN,NaN,NaN,16,16,8,8,6,Economie,Mathematiques,Economie
1,ET002,NaN,NaN,NaN,7,15,20,20,13,Art,Programmation,Design
2,ET003,NaN,NaN,NaN,14,17,17,17,5,Sciences,Statistique,statistique
3,ET004,NaN,NaN,NaN,7,16,8,8,19,Informatique,Dessin,Design
4,ET005,NaN,NaN,NaN,9,13,19,19,15,Lettres,Communication écrite,Littérature
...,...,...,...,...,...,...,...,...,...,...,...,...
1142,ET1145,NaN,NaN,NaN,3,3,3,18,6,Éthique,cybersécurité,Cybersécurité
1143,ET1146,NaN,NaN,NaN,20,20,20,0,13,Volontariat,mathématiques,Sociologie
1144,ET1147,NaN,NaN,NaN,19,19,5,6,5,Robotique,chimie,Intelligence artificielle
1145,ET1148,NaN,NaN,NaN,20,20,17,5,19,Mathématiques,architecture,Architecture
1146,ET1149,NaN,NaN,NaN,20,20,20,20,20,Écriture créative,Dessin,Peinture

In [31]:
# Conversion des variables catégorielles en variables numériques
le_interets = LabelEncoder()
le_comp = LabelEncoder()
df['Interets'] = le_interets.fit_transform(df['Interets '])
df['Compétences'] = le_comp.fit_transform(df['Compétences'])

# Séparation des variables indépendantes (X) et de la variable cible (y)
X = df[['NotesMaths', 'NotesFrançais', 'NotesPhysiques', 'NotesChimie', 'NotesAnglais', 'Interets_1', 'Interets_2']]
y = df['ChoixOrientation']  # Changez cela selon votre cas d'utilisation, par exemple 'ChoixInformatique'


# Division des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)


# Initialisation du modèle k-NN
knn = KNeighborsClassifier(n_neighbors=3)  # Vous pouvez ajuster le nombre de voisins (k) selon vos besoins

# Entraînement du modèle
knn.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = knn.predict(X_test)

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
print(f"Précision du modèle k-NN : {accuracy}")

KeyError: 'Interets '

In [ ]:
nouvel_etudiant = {
    'NotesMaths': 20,
    'NotesFrançais': 12,
    'NotesPhysiques': 0,
    'NotesChimie': 0,
    'NotesAnglais': 0,
    'Interets': 'Design',  
    'Compétences': 'Design'  
}

nouvel_etudiant_df = pd.DataFrame([nouvel_etudiant])

nouvel_etudiant_df

# Conversion des variables catégorielles en variables numériques en utilisant les mêmes encodeurs que lors de l'entraînement
nouvel_etudiant_df['Interets'] = le_interets.fit_transform(nouvel_etudiant_df['Interets'])
nouvel_etudiant_df['Compétences'] = le_comp.fit_transform(nouvel_etudiant_df['Compétences'])


# Prédiction avec le modèle k-NN
prediction = knn.predict(nouvel_etudiant_df)

# Affichage de la recommandation
print(f"Recommandation d'orientation pour le nouvel étudiant : {prediction}")

Recommandation d'orientation pour le nouvel étudiant : ['Agronomie']