In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


etudiants = pd.read_csv("TB_ETUDIANT.csv", encoding='latin-1', delimiter=";")

#creation de dataframe
df = pd.DataFrame(etudiants)

df

,ID_ETUDIANT,Sexe,MoyenneBac,Orientation,NotesMaths,NotesFrançais,NotesPhysChimie,NotesSVT,NotesAnglais,Interets1,Interets2,choixOrientation
0,ET001,F,15.0,L,16.0,16.0,12.75,8.00,6.0,Biologie,Biosciences,Chimie
1,ET002,F,10.0,S,7.0,15.0,20.00,20.00,13.0,Finance / Comptabilité / Statistiques,Business Administration,Business Administration
2,ET003,F,10.0,S,14.0,17.0,17.00,17.00,9.0,Physiques,Biosciences,Biosciences
3,ET004,F,15.0,S,7.0,16.0,12.75,8.00,19.0,Informatique,Genie Logiciel,Informatique
4,ET005,F,12.0,S,9.0,13.0,19.00,19.00,15.0,Informatique,Genie Logiciel,Genie Logiciel
...,...,...,...,...,...,...,...,...,...,...,...,...
1142,ET1145,M,10.0,S,9.0,13.5,14.00,18.00,6.0,Banque / Assurance,Mathematiques,Finance Banque
1143,ET1146,M,14.0,S,20.0,20.0,20.00,12.00,13.0,Anglais,Genie Logiciel,Genie Logiciel
1144,ET1147,M,13.0,S,19.0,19.0,10.00,12.25,9.0,Chimie,Psychologie,Biosciences
1145,ET1148,F,10.0,S,20.0,20.0,17.00,13.50,19.0,Anglais,Genie Logiciel,Genie Logiciel
1146,ET1149,F,12.0,S,17.0,20.0,20.00,20.00,18.0,Biologie,Psychologie,Psychologie

In [9]:
# Séparation des variables indépendantes (X) et de la variable cible (y)
X = df[['MoyenneBac', 'NotesMaths', 'NotesFrançais', 'NotesPhysChimie', 'NotesSVT', 'NotesAnglais',  'Interets1', 'Interets2']]
y = df['choixOrientation']


# Division des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)


categorical_cols = ['Interets1', 'Interets2']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), categorical_cols)
    ],
    remainder='passthrough'
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)



# Evaluation du modele
accuracy = accuracy_score(y_test, y_pred)
print(f'Precision du modele de regression logistique: {accuracy}')

Precision du modele de regression logistique: 0.7652173913043478

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [10]:
# Nouvel étudiant pour la prédiction
nouvel_etudiant = {
    'MoyenneBac' : 15,
    'NotesMaths': 19,
    'NotesFrançais': 19,
    'NotesPhysChimie': 19,
    'NotesSVT': 19,
    'NotesAnglais': 15,
    'Interets1': 'Informatique',  
    'Interets2': 'Biologie'  
}

# Création d'un DataFrame pour le nouvel étudiant
nouvel_etudiant_df = pd.DataFrame([nouvel_etudiant])

# Prédiction pour le nouvel étudiant
prediction_nouvel_etudiant = pipeline.predict(nouvel_etudiant_df)

# Affichage de la prédiction pour le nouvel étudiant
print(f"Prédiction d'orientation pour le nouvel étudiant : {prediction_nouvel_etudiant}")

Prédiction d'orientation pour le nouvel étudiant : ['Informatique']