In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


etudiants = pd.read_csv("TB_ETUDIANT.csv", encoding='latin-1', delimiter=";")

#creation de dataframe
df = pd.DataFrame(etudiants)

df

,ID_ETUDIANT,Sexe,MoyenneBac,NotesMaths,NotesFrançais,NotesPhysChimie,NotesSVT,NotesAnglais,Interets1,Interets2,Orientation,Licence
0,ET001,F,15.0,16.0,16.0,12.75,8.00,6.0,agriculture,agro-alimentaire,agronomie,oui
1,ET002,F,10.0,7.0,15.0,20.00,20.00,13.0,Chimie,sociologie,Biologie,oui
2,ET003,F,10.0,14.0,17.0,17.00,17.00,9.0,Architecture,Mathematiques,Genie civil,oui
3,ET004,F,15.0,7.0,16.0,12.75,8.00,19.0,Informatique,Multimedia,Informatique,non
4,ET005,F,12.0,9.0,13.0,19.00,19.00,15.0,sociologie,Social,Medecine,oui
...,...,...,...,...,...,...,...,...,...,...,...,...
1142,ET1145,M,10.0,9.0,13.5,14.00,18.00,6.0,Assurance banque,Mathematiques,Hotellerie,oui
1143,ET1146,M,14.0,20.0,20.0,20.00,12.00,13.0,Anglais,Mathematiques,informatique,oui
1144,ET1147,M,13.0,19.0,19.0,10.00,12.25,9.0,Mathematiques,Genie civil,architecture,oui
1145,ET1148,F,10.0,20.0,20.0,17.00,13.50,19.0,Anglais,informatique,informatique,oui
1146,ET1149,F,12.0,17.0,20.0,20.00,20.00,18.0,Biologie,Psychologie,Psychologie,oui

In [2]:
from sklearn.metrics import mean_squared_error
# Séparation des variables indépendantes (X) et de la variable cible (y)
X = df[['MoyenneBac', 'NotesMaths', 'NotesFrançais', 'NotesPhysChimie', 'NotesSVT', 'NotesAnglais',  'Interets1', 'Interets2']]
y = df['Licence']


# Division des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)


categorical_cols = ['Interets1', 'Interets2']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), categorical_cols)
    ],
    remainder='passthrough'
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)



# Evaluation du modele
accuracy = accuracy_score(y_test, y_pred)
print(f'Precision du modele de regression logistique: {accuracy}')

Precision du modele de regression logistique: 0.5739130434782609

c:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [3]:
# Nouvel étudiant pour la prédiction
nouvel_etudiant = {
    'MoyenneBac' : 14,
    'NotesMaths': 12,
    'NotesFrançais': 7,
    'NotesPhysChimie': 12,
    'NotesSVT': 10,
    'NotesAnglais': 8,
    'Interets1': 'Physiques',  
    'Interets2': 'Informatique' 
}

# Création d'un DataFrame pour le nouvel étudiant
nouvel_etudiant_df = pd.DataFrame([nouvel_etudiant])

# Prédiction pour le nouvel étudiant
prediction_nouvel_etudiant = pipeline.predict(nouvel_etudiant_df)

print(f'La prédiction pour le nouvel étudiant est : {prediction_nouvel_etudiant[0]}')

class_labels = pipeline.classes_
probabilities = pipeline.predict_proba(nouvel_etudiant_df)

for i, prob in enumerate(probabilities[0]):
    print(f"Probabilité de la classe {class_labels[i]} : {prob:.2%}")

La prédiction pour le nouvel étudiant est : oui
Probabilité de la classe non : 35.39%
Probabilité de la classe oui : 64.61%